In [1]:
import qif
import numpy as np

In [14]:
# Define C
# C = np.array(([1, 0], [0, 1], [1, 0], [0, 1]))
C = np.array(([3/4, 1/4], [1/4, 3/4]))
print(C)

[[0.75 0.25]
 [0.25 0.75]]


In [15]:
# Define J
# J = np.array(([1/8, 1/16, 1/4, 1/16], [1/16, 1/4, 1/16, 1/8]))
J = np.array(([6/15, 4/15], [1/15, 4/15]))
print(J)

[[0.4        0.26666667]
 [0.06666667 0.26666667]]


In [17]:
rho = J.sum(axis=1)
pi = J.sum(axis=0)
print(rho)
print(pi)

[0.66666667 0.33333333]
[0.46666667 0.53333333]


In [18]:
qif.measure.bayes_vuln.mult_leakage(pi, C)

1.40625

In [19]:
B = J/rho.reshape(-1, 1)
print(B)

[[0.6 0.4]
 [0.2 0.8]]


In [20]:
BC = B.dot(C)
print(BC)

[[0.55 0.45]
 [0.35 0.65]]


In [21]:
qif.measure.bayes_vuln.mult_leakage(rho, BC)

0.9999999999999999